### ISSUE TITLE
svelte3 support

### ISSUE THREAD

**Issue by cudr** [sveltejs/svelte-loader#74] opened 2019-01-13 05:22 UTC
Have this error with svelte3:

`proxy.js:135 TypeError: Class constructor SvelteComponentDev cannot be invoked without 'new'
    at new Layout (_layout.html:2)
    at proxyComponent._register (proxy.js:128)
    at new proxyComponent (proxy.js:54)
    at render (client.js:183)
    at client.js:148
`

looks like problem with svelte-dev-helper. How i can resolve it?

**Comment by ekhaled** [comment] 2019-01-14 09:54
HMR is not supported for svelte v3 yet.
Please set `hotReload: false` in the webpack config while testing out v3.

**Comment by rnenjoy** [comment] 2019-04-26 14:47
Considering switching from Vue/Nuxt to Svelte. But lack of Hot reloading is really a bummer. Watching this

**Comment by Vages** [comment] 2019-08-08 13:05
@ekhaled's solution solved the following problem for me: Mounting a (Svelte) component that didn't import any other components worked all right. But once I started importing other components, things went awry, with the following messages showing up in the app's console:

```
TypeError: Cannot read property 'fragment' of undefined
    at Object.c (webpack-internal:///./src/feedbackWindow/App.svelte:17)
    at init (webpack-internal:///./node_modules/svelte/internal/index.js:1255)
    at new App (webpack-internal:///./src/feedbackWindow/App.svelte:54)
    at proxyComponent._register (webpack-internal:///./node_modules/svelte-dev-helper/lib/proxy.js:135)
    at new proxyComponent (webpack-internal:///./node_modules/svelte-dev-helper/lib/proxy.js:61)
    at Module.eval (webpack-internal:///./src/feedbackWindow/main.js:22)
    at eval (webpack-internal:///./src/feedbackWindow/main.js:46)
    at Module../src/feedbackWindow/main.js (feedback.bundle.js:6017)
    at __webpack_require__ (feedback.bundle.js:727)
    at fn (feedback.bundle.js:101)
    at Object.9 (feedback.bundle.js:6033)
    at __webpack_require__ (feedback.bundle.js:727)
    at feedback.bundle.js:794
    at feedback.bundle.js:797
```
```
Uncaught TypeError: Cannot read property '_debugName' of undefined
    at new proxyComponent (webpack-internal:///./node_modules/svelte-dev-helper/lib/proxy.js:63)
    at Module.eval (webpack-internal:///./src/feedbackWindow/main.js:22)
    at eval (webpack-internal:///./src/feedbackWindow/main.js:46)
    at Module../src/feedbackWindow/main.js (feedback.bundle.js:6017)
    at __webpack_require__ (feedback.bundle.js:727)
    at fn (feedback.bundle.js:101)
    at Object.9 (feedback.bundle.js:6033)
    at __webpack_require__ (feedback.bundle.js:727)
    at feedback.bundle.js:794
    at feedback.bundle.js:797
```

Just posting to make it easier for people to reach this issue by searching.

**Comment by will-wow** [comment] 2019-09-03 23:56
Just making sure, is HMR still not supported for Svelte 3? The docs seem to suggest that `hotReload: true` will work, but maybe that's only for Svelte 2?

If so, I'd be happy to put up a little PR to make a note that Svelte 3 HMR is incoming, so future don't spend time trying to debug why HMR isn't working.

**Comment by gui-killer** [comment] 2020-06-22 09:23
I meet a problem that is the same with @Vages 's. I used "svelte-loader" in webpack@v4.43.0 with the code-splitting and HMR features disabled. 
The error messages in console are as below:

proxy.js:135 
TypeError: Cannot read property 'fragment' of undefined
    at Object.c (App.svelte:5)
    at init (index.mjs:1457)
    at new App (App.svelte:17)
    at proxyComponent._register (proxy.js:128)
    at new proxyComponent (proxy.js:54)
    at Module../src/index.js (index.js:4)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at Object.1 (App.svelte:17)
    at __webpack_require__ (bootstrap:789)

proxy.js:56 
Uncaught TypeError: Cannot read property '_debugName' of undefined
    at new proxyComponent (proxy.js:56)
    at Module../src/index.js (index.js:4)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at Object.1 (App.svelte:17)
    at __webpack_require__ (bootstrap:789)
    at bootstrap:856
    at bootstrap:856

**Comment by gui-killer** [comment] 2020-06-22 09:40
@Vages Formerly I had the same problem with you, but it finally solved it by doing these:
1. Set the `hotReload` to `false` in `svelte-loader`'s option.
2. Set the `hot` to `false` in webpack-dev-server  if you use it.
3. Remove the webpack-dev-server client from the `entry` of your webpack.config.js.

**Comment by Vages** [comment] 2020-06-24 16:54
Thanks for the advice, @gui-killer. I'm sure it will be of help the next time I use it. However, the project in question needed the webpack-dev-server entry-point and hot=true in webpack dev server because some other frameworks we used at the same time required it.

**Comment by rendall** [comment] 2020-08-27 07:54
As a newbie to Svelte, I'm going to leave this here in case it prompts someone with more experience to have insight. Maybe we can crowdsource a solution.

The error `TypeError: Cannot read property 'fragment' of undefined`

is thrown in the source `webpack:///./node_modules/svelte/internal/index.mjs` at line `1461` which is `$$.fragment && $$.fragment.c();`, so it appears that `$$` is `undefined`

The code fragment surrounding that line is below [1]

There is no `index.mjs` file in the repo, given that it's a compiled file, but I think that line is [here](https://github.com/sveltejs/svelte/blob/ec0f79c5af3113bedf0a5e9ae1f5f521328fcd30/src/runtime/internal/Component.ts#L156) <https://github.com/sveltejs/svelte/blob/ec0f79c5af3113bedf0a5e9ae1f5f521328fcd30/src/runtime/internal/Component.ts#L156>


[1] It seems that `create_fragment` and `options.hydrate` are evaluating to `false` while `options.target` is `true`. I don't know enough about the Svelte internals to know what that means, nor why the first line `$$.fragment = create_fragment ? create_fragment($$.ctx) : false;` does *not* throw.
```
    // `false` as a special case of no DOM component
    $$.fragment = create_fragment ? create_fragment($$.ctx) : false;
    if (options.target) {
        if (options.hydrate) {
            const nodes = children(options.target);
            // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
            $$.fragment && $$.fragment.l(nodes);
            nodes.forEach(detach);
        }
        else {
            // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
            $$.fragment && $$.fragment.c();
        }
        if (options.intro)
            transition_in(component.$$.fragment);
        mount_component(component, options.target, options.anchor);
        flush();
    }
```

**Comment by rendall** [comment] 2020-08-27 08:22
As for the next error, for me it is:
```
Uncaught TypeError: Cannot read property '_debugName' of undefined
    at new proxyComponent (proxy.js:56)
    at Module../src/main.ts (main.ts:3)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at Object.1 (bundle.js:13627)
    at __webpack_require__ (bootstrap:789)
    at bootstrap:856
    at bootstrap:856
```

The first entry in the stack trace leads to this line (`56`) in `webpack:///./node_modules/svelte-dev-helper/lib/proxy.js` (which is this repo)

[`      this._debugName = this.proxyTarget._debugName || getDebugName(this.id);`](https://github.com/ekhaled/svelte-dev-helper/blob/d16c2e5265f6513ac07a078d4e42ef0e4764a934/lib/proxy.js#L56)

which is in the constructor for `proxyComponent` as below. I think this bug may be fixed by changing the line to 

`      this._debugName = getDebugName(this.id) || this.proxyTarget._debugName ;`

because I suspect that `this.proxyTarget` evaluates to `undefined` and so `this.proxyTarget._debugName ;` errors before the next expression can be evaluated.

But, again, I know very little about the codebase, so it may not fix the error in `svelte`

```
class proxyComponent {

    constructor(options) {
      this.id = id;
      this.__mountpoint = null;
      this.__anchor = null;
      this.__insertionPoint = null;
      this.__mounted = false;

      this._register(options);

      this._debugName = this.proxyTarget._debugName || getDebugName(this.id);

      // ---- forwarded methods ----
      const self = this;
      forwardedMethods.forEach(function(method) {
        self[method] = function() {
          return self.proxyTarget[method].apply(self.proxyTarget, arguments);
        };
      });
      // ---- END forwarded methods ----
    }
```

**Comment by rixo** [comment] 2020-08-27 08:40
@rendall Hey! I went down a very similar path as you [some time ago](https://github.com/sveltejs/svelte-loader/issues/92#issue-444667953). Indeed, there are not a whole lot of things to adapt in this codebase to make it work with Svelte 3.

Eventually this led me to the development of [svelte-hmr](https://github.com/rixo/svelte-hmr). You may want to check the README of this project. We now have community plugins with HMR support both for Webpack and Rollup, and even super fast, almost instant, options with Nollup and Svite!

If you're interested in contributing to HMR, you might want to check what can be enhanced in those projects, instead of doing it all from scratch again ;)

**Comment by rendall** [comment] 2020-08-27 09:02
Coo'. I swapped in `svelte-loader-hot` and it seems to work out of the box, so good on ye.  I even already issued a little tiny PR for a typo in the README. Thanks!  If I think if any enhancements I will let you know.

I do feel a bit of an obligation to help out here, where possible, but now I can hot reload. Groovy.

**Comment by rixo** [comment] 2020-08-27 11:20
@rendall BTW if you're in search of a Svelte HMR challenge for yourself, there is the Sapper + Nollup + HMR thing that I've been meaning to address but lacked time thus far...

I've got a POC working, and we want to go the rest of the way by integrating that cleanly into Sapper (and this requires discussion and PR at Nollup too).

@antony was interested in working on this, especially on the Sapper part.

There's been some discussion, and link to my POC is available in this issue: https://github.com/sveltejs/sapper/issues/1207#issuecomment-642223370

I'm mentioning this because this work seems very much aligned with the debugging skills you've displayed previously. Maybe that's something you'll want to play with :)

**Comment by benmccann** [comment] 2021-01-13 20:35
Closing as duplicate of https://github.com/sveltejs/svelte-loader/issues/92

**Closed by benmccann** 2021-01-13 20:35 UTC
