### ISSUE TITLE
Remove ExtractTextPlugin from README

### ISSUE THREAD

**Issue by gavinr** [sveltejs/svelte-loader#119] opened 2020-03-10 19:53 UTC
The [readme](https://github.com/sveltejs/svelte-loader/blob/master/README.md) mentions `ExtractTextPlugin`, but that plugin is deprecated, in favor of [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin). The [sveltejs/template-webpack](https://github.com/sveltejs/template-webpack) is actually using `mini-css-extract-plugin`, so I assume this change is well-known it just has not gotten updated in the readme yet.

**Comment by benmccann** [comment] 2020-09-08 20:53
Closing as duplicate of https://github.com/sveltejs/svelte-loader/issues/95. A PR to update this would be welcomed

**Closed by benmccann** 2020-09-08 20:53 UTC
